# Log level and assert behaviour
option(SIMPLELOG_ASSERT_ENABLED "Enable or disable asserts." ON)
set(SIMPLELOG_LOG_LEVEL "LOG_LEVEL_VERBOSE" CACHE STRING "The log level.")
set_property(CACHE SIMPLELOG_LOG_LEVEL PROPERTY STRINGS LOG_LEVEL_VERBOSE LOG_LEVEL_DEBUG LOG_LEVEL_INFO LOG_LEVEL_WARNING LOG_LEVEL_ERROR LOG_LEVEL_PANIC LOG_LEVEL_DISABLED)

# Log max length
set(SIMPLELOG_MAX_LINE_LENGTH "256" CACHE STRING "The max length of each log entry.")

# Asynchronous logging max queue size
set(SIMPLELOG_ASYNCHRONOUS_MAX_QUEUE_SIZE "16384" CACHE STRING "The max queue size for asynchronous logging.")

# Log max length
set(SIMPLELOG_CONFIG_INI "" CACHE STRING "The simplelog configuration file path if any.")

# Set according defines
if (SIMPLELOG_ASSERT_ENABLED)
  set(DEFINITIONS ${DEFINITIONS} -DLOG_ASSERT_ENABLED)
endif()
set(DEFINITIONS ${DEFINITIONS} -DLOG_LEVEL=${SIMPLELOG_LOG_LEVEL})
set(DEFINITIONS ${DEFINITIONS} -DLOG_MAX_LINE_LENGTH=${SIMPLELOG_MAX_LINE_LENGTH})
set(DEFINITIONS ${DEFINITIONS} -DLOG_ASYNCHRONOUS_MAX_QUEUE_SIZE=${SIMPLELOG_ASYNCHRONOUS_MAX_QUEUE_SIZE})
set(DEFINITIONS ${DEFINITIONS} -DLOG_CONFIG_INI=\"${SIMPLELOG_CONFIG_INI}\")
add_definitions(${DEFINITIONS})
